/* Curated content with original animal illustrations. Sources reviewed 4 October 2026. */
const ECHOES_DATA = {
  reviewed: "4 October 2026",
  species: [
    {
      id: "mammoth",
      number: "001",
      name: "Woolly mammoth",
      scientific: "Mammuthus primigenius",
      status: "extinct",
      place: "Northern hemisphere",
      range: "Northern Eurasia and North America",
      date: "~4,000 years ago",
      dateDetail: "Last island populations: about 4,000 years ago",
      image: "assets/animals/mammoth.jpg",
      alt: "Original realistic illustration of a woolly mammoth in a snowy Arctic landscape",
      summary: "An Ice Age giant. A final refuge on a remote Arctic island.",
      paragraphs: [
        "Thick hair and cold-weather adaptations helped woolly mammoths live across northern landscapes. As the Ice Age ended, their open habitats contracted.",
        "Small island populations outlasted the mainland herds. The last known mammoths on Wrangel Island survived until about 4,000 years ago.",
      ],
      evidence:
        "Climate, habitat change, and hunting have been studied as contributors. The cause of the final Wrangel Island extinction remains uncertain.",
      timelineTitle: "A final refuge for the giants.",
      timelineText:
        "Long after mainland herds disappeared, mammoths persisted on Arctic islands. Wrangel Island held the last known population.",
      sourceName: "Natural History Museum",
      sourceTitle: "Were all mammoths woolly?",
      conservation: "Extinct",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "55% 42%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "dodo",
      number: "002",
      name: "Dodo",
      scientific: "Raphus cucullatus",
      status: "extinct",
      place: "Mauritius",
      range: "Mauritius, Indian Ocean",
      date: "Late 1600s",
      dateDetail: "Disappeared in the late seventeenth century",
      image: "assets/animals/dodo.jpg",
      alt: "Original realistic illustration of a dodo on a tropical Mauritian shoreline",
      summary: "A flightless island bird. An enduring symbol of loss.",
      paragraphs: [
        "The dodo evolved on Mauritius, an island without the land predators introduced by later settlers. It was a flightless bird related to pigeons.",
        "Hunting and introduced animals, including pigs and rats, disrupted its world. It disappeared within a century of Dutch arrival in 1598.",
      ],
      evidence:
        "1662 is a widely cited last reliable sighting; later sightings and the exact extinction date are debated. The illustration is a reconstruction, not evidence of its precise appearance.",
      timelineTitle: "An island falls silent.",
      timelineText:
        "The dodo disappeared from Mauritius in the late 1600s. Introduced animals and hunting transformed a once-isolated island ecosystem.",
      sourceName: "Natural History Museum",
      sourceTitle:
        "The dodo bird: the real facts about this icon of extinction",
      conservation: "Extinct",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "75% 48%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "smilodon",
      number: "003",
      name: "Smilodon",
      scientific: "Smilodon fatalis",
      status: "extinct",
      place: "Americas",
      range: "North America",
      date: "~11,000 years ago",
      dateDetail: "Around the end of the last Ice Age",
      image: "assets/animals/smilodon.jpg",
      alt: "Original realistic illustration of a smilodon in a cold open landscape",
      summary: "Powerful forelimbs. Extraordinary teeth. An Ice Age hunter.",
      paragraphs: [
        "Smilodon fatalis was a muscular saber-toothed cat built to ambush large prey. Fossils at La Brea Tar Pits reveal a strongly built animal and evidence of a diet that included bison.",
        "It disappeared around the end of the last Ice Age. Its saber-toothed lineage was distinct from modern tigers.",
      ],
      evidence:
        "Dates differ between sites and studies. La Brea Tar Pits describes extinction around 11,000 years ago. Fur colour and markings are uncertain because soft tissues were not preserved there.",
      timelineTitle: "The end of an Ice Age hunter.",
      timelineText:
        "As the last Ice Age ended, Smilodon vanished. Its fossils preserve clues to a powerful predator and a lost ecosystem.",
      sourceName: "La Brea Tar Pits",
      sourceTitle: "Suiting Up for Smilodon",
      conservation: "Extinct",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "50% 30%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "tiger",
      number: "004",
      name: "Tiger",
      scientific: "Panthera tigris",
      status: "endangered",
      place: "Asia",
      range: "Forests, grasslands, and wetlands across parts of Asia",
      date: "Still with us",
      dateDetail: "Endangered; conservation remains essential",
      image: "assets/animals/tiger.jpg",
      alt: "Original realistic illustration of a tiger walking through lush forest",
      summary: "A living icon of the wild. A future we can still influence.",
      paragraphs: [
        "Tigers are the largest living cats. They need connected habitats, sufficient prey, and protection from poaching.",
        "Habitat loss and conflict with people continue to threaten them. Conservation supports some recovering populations, but progress is uneven across their range.",
      ],
      evidence:
        "WWF lists the species as Endangered. Regional and subspecies situations differ. This archive does not present a live population count.",
      timelineTitle: "A story still unfolding.",
      timelineText:
        "The tiger remains endangered. Protecting habitats and reducing poaching can help its story continue.",
      sourceName: "WWF",
      sourceTitle: "Tiger",
      conservation: "Endangered",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "28% 50%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "thylacine",
      name: "Thylacine",
      scientific: "Thylacinus cynocephalus",
      status: "extinct",
      conservation: "Extinct",
      place: "Tasmania",
      range:
        "Historically Australia and New Guinea; last known population in Tasmania",
      date: "1936",
      dateDetail: "Last known animal died on 7 September 1936",
      summary:
        "A striped marsupial. A warning about protection that came too late.",
      paragraphs: [
        "Often called the Tasmanian tiger, the thylacine was a carnivorous marsupial. Its name and stripes did not make it a relative of living tigers.",
        "Hunting, bounties, habitat destruction, and other pressures reduced its Tasmanian population. The last known animal died at Beaumaris Zoo in Hobart shortly after legal protection arrived.",
      ],
      evidence:
        "1936 marks the death of the last known captive animal, rather than a precisely observed final death in the wild. Later reports have not provided conclusive evidence of survival.",
      sourceName: "National Museum of Australia",
      sourceTitle: "Extinction of thylacine",
      number: "005",
      image: "assets/animals/thylacine.png",
      alt: "Original realistic illustration of a thylacine in Tasmanian wilderness",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "42% 50%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "great-auk",
      name: "Great auk",
      scientific: "Pinguinus impennis",
      status: "extinct",
      conservation: "Extinct",
      place: "North Atlantic",
      range: "Rocky islands and coasts of the North Atlantic",
      date: "Mid-1800s",
      dateDetail:
        "Last breeding pair killed in 1844; a later sighting was recorded in 1852",
      summary: "Built for the sea. Vulnerable on the shores where it nested.",
      paragraphs: [
        "The great auk was a flightless seabird that dived for fish in cold North Atlantic waters. Dense breeding colonies gathered on rocky islands.",
        "People hunted it for meat, feathers, fat, and oil. As it became rare, demand for specimens added pressure. The last breeding pair was killed on Eldey, Iceland, in 1844.",
      ],
      evidence:
        "Extinction dates are often simplified to 1844. The Natural History Museum also reports a later live sighting in 1852, so this archive uses a broader date.",
      sourceName: "Natural History Museum",
      sourceTitle: "Worlds collide: the great auk",
      number: "006",
      image: "assets/animals/great-auk.jpg",
      alt: "Original realistic illustration of a great auk on a rocky North Atlantic coast",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "66% 50%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "passenger-pigeon",
      name: "Passenger pigeon",
      scientific: "Ectopistes migratorius",
      status: "extinct",
      conservation: "Extinct",
      place: "North America",
      range: "Forests of eastern North America",
      date: "1914",
      dateDetail: "Last known bird, Martha, died on 1 September 1914",
      summary:
        "Once a sky full of wings. Abundance was no guarantee of survival.",
      paragraphs: [
        "Passenger pigeons travelled in enormous flocks across eastern North America. Their story challenges the idea that a very common animal cannot disappear.",
        "Commercial hunting and the loss of forests devastated the population. Martha, the last known passenger pigeon, died at Cincinnati Zoo in 1914.",
      ],
      evidence:
        "Historical flock-size estimates vary. The date shown is the death of the last known captive individual; it does not identify the last bird to die in the wild.",
      sourceName: "Natural History Museum",
      sourceTitle:
        "Passenger pigeon: how the world’s most common bird went extinct",
      number: "007",
      image: "assets/animals/passenger-pigeon.jpg",
      alt: "Original realistic illustration of a passenger pigeon perched above a forested valley",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "50% 28%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "quagga",
      name: "Quagga",
      scientific: "Equus quagga quagga",
      status: "extinct",
      conservation: "Extinct",
      place: "South Africa",
      range: "The Karoo and southern Free State, South Africa",
      date: "1883",
      dateDetail: "Last known animal died on 12 August 1883",
      summary:
        "Stripes that faded along its body. A lineage lost from the plains.",
      paragraphs: [
        "The quagga was a subspecies of the plains zebra, with strong stripes toward the front and a much less striped rear. It lived in southern Africa.",
        "Settlers hunted quaggas and treated them as competitors for livestock grazing. The last known captive quagga died at Amsterdam Zoo in 1883.",
      ],
      evidence:
        "This is an extinct subspecies, rather than an extinct zebra species. Modern selectively bred zebras resembling its coat pattern should not be mistaken for surviving original quaggas.",
      sourceName: "The Quagga Project",
      sourceTitle: "What was the quagga?",
      number: "008",
      image: "assets/animals/quagga.jpg",
      alt: "Original realistic illustration of a quagga in open South African grassland",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "45% 50%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "sea-cow",
      name: "Steller’s sea cow",
      scientific: "Hydrodamalis gigas",
      status: "extinct",
      conservation: "Extinct",
      place: "Bering Sea",
      range: "Shallow coastal waters around the Commander Islands",
      date: "1768",
      dateDetail: "Last known population disappeared by 1768",
      summary:
        "A gentle kelp grazer. Gone within decades of scientific discovery.",
      paragraphs: [
        "Steller’s sea cow was a large marine mammal related to living dugongs and manatees. The last known population fed on kelp near the Commander Islands in the Bering Sea.",
        "Georg Wilhelm Steller described it in 1741. Intensive hunting followed, and the remaining population disappeared by 1768.",
      ],
      evidence:
        "Surviving descriptions are limited. Historical artwork offers an interpretation of its appearance; it is not a photograph or a complete anatomical record.",
      sourceName: "Natural History Museum",
      sourceTitle:
        "Steller’s sea cow: the first historical extinction of a marine mammal at human hands",
      number: "009",
      image: "assets/animals/sea-cow.jpg",
      alt: "Original realistic illustration of Steller’s sea cow in cold coastal kelp waters",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "50% 50%",
      imageFit: "contain",
      imageBackground: "#f1eee5",
    },
    {
      id: "giant-moa",
      name: "South Island giant moa",
      scientific: "Dinornis robustus",
      status: "extinct",
      conservation: "Extinct",
      place: "New Zealand",
      range: "South Island and nearby islands, New Zealand",
      date: "After human arrival",
      dateDetail: "Extinct within a few centuries of human settlement",
      summary:
        "A towering, wingless browser. One of New Zealand’s lost giants.",
      paragraphs: [
        "The South Island giant moa was one of nine moa species. Females were much larger than males, and these birds browsed a wide variety of vegetation.",
        "Moa had no wings, even as small vestiges. Hunting after human arrival drove giant moa to extinction; habitat burning likely added to the pressure.",
      ],
      evidence:
        "“Moa” describes several species. This story concerns Dinornis robustus. Fossils, feathers, and DNA help researchers reconstruct its biology, but the exact final extinction date is uncertain.",
      sourceName: "New Zealand Birds Online",
      sourceTitle: "South Island giant moa | Moa nunui",
      number: "010",
      image: "assets/animals/giant-moa.jpg",
      alt: "Original realistic illustration of a South Island giant moa in a New Zealand alpine landscape",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "50% 50%",
      imageFit: "contain",
      imageBackground: "#111511",
    },
    {
      id: "irish-elk",
      name: "Irish elk",
      scientific: "Megaloceros giganteus",
      status: "extinct",
      conservation: "Extinct",
      place: "Eurasia",
      range: "Across parts of Eurasia, beyond Ireland",
      date: "~8,000 years ago",
      dateDetail:
        "Last known populations survived in central Russia until about 8,000 years ago",
      summary:
        "Extraordinary antlers. A giant deer with a wider world than its name.",
      paragraphs: [
        "Despite its common name, the Irish elk was a giant deer that lived far beyond Ireland. Males carried exceptionally broad antlers.",
        "Most European populations disappeared around the end of the Ice Age. Some survived longer in central Russia as landscapes and vegetation changed.",
      ],
      evidence:
        "Dates differ across its former range. Changing climate, vegetation, and possible hunting pressures are studied as contributors; a single simple cause would overstate the evidence.",
      sourceName: "Natural History Museum",
      sourceTitle: "Irish elk: the giant deer",
      number: "011",
      image: "assets/animals/irish-elk.jpg",
      alt: "Original realistic illustration of an Irish elk in a glacial valley landscape",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "50% 40%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "asian-elephant",
      name: "Asian elephant",
      scientific: "Elephas maximus",
      status: "endangered",
      conservation: "Endangered",
      place: "South & Southeast Asia",
      range: "Forests and grasslands across South and Southeast Asia",
      date: "Still with us",
      dateDetail: "Endangered; habitat connections are essential",
      summary: "An ancient traveller. A future that depends on room to roam.",
      paragraphs: [
        "Asian elephants move through forests and grasslands, dispersing seeds and opening pathways used by other wildlife. Family groups are led by an experienced female.",
        "Habitat loss and fragmentation interrupt their routes. Conservation connects habitats and helps communities manage conflict where elephants and people share the landscape.",
      ],
      evidence:
        "The species is Endangered. Individual subspecies and regional populations can have different risk levels. The illustration depicts an Asian elephant.",
      sourceName: "WWF",
      sourceTitle: "Asian elephants",
      number: "012",
      image: "assets/animals/asian-elephant.jpg",
      alt: "Original realistic illustration of an Asian elephant in a tropical clearing",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "43% 50%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "forest-elephant",
      name: "African forest elephant",
      scientific: "Loxodonta cyclotis",
      status: "endangered",
      conservation: "Critically endangered",
      place: "West & Central Africa",
      range: "Tropical rainforests of West and Central Africa",
      date: "Still with us",
      dateDetail:
        "Critically endangered; ivory poaching and habitat loss remain major threats",
      summary:
        "A rainforest gardener. A small footprint with an enormous role.",
      paragraphs: [
        "Smaller than African savanna elephants, forest elephants inhabit dense tropical forests. They eat fruit and disperse seeds, helping shape the next generation of trees.",
        "Ivory poaching and the loss of connected forest habitat threaten their survival. Their slow reproductive rate makes recovery from heavy losses difficult.",
      ],
      evidence:
        "African forest elephants are a distinct species, not simply savanna elephants photographed in a forest. WWF reports the IUCN’s Critically Endangered classification adopted in 2021.",
      sourceName: "WWF",
      sourceTitle: "African forest elephants",
      number: "013",
      image: "assets/animals/forest-elephant.jpg",
      alt: "Original realistic illustration of an African forest elephant in dense rainforest",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "50% 50%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "amur-leopard",
      name: "Amur leopard",
      scientific: "Panthera pardus orientalis",
      status: "endangered",
      conservation: "Critically endangered",
      place: "Russian Far East & China",
      range: "Temperate forests of the Russian Far East and northeastern China",
      date: "Still with us",
      dateDetail:
        "Critically endangered; protection of habitat and prey remains vital",
      summary: "A quiet hunter of cold forests. Every safe landscape matters.",
      paragraphs: [
        "The Amur leopard is a leopard subspecies adapted to temperate forests at the northern edge of the leopard’s range. It is a solitary, powerful predator.",
        "Poaching threatens both leopards and their prey. Protecting forests and rebuilding prey populations are essential to sustained recovery.",
      ],
      evidence:
        "The status shown applies to the Amur leopard subspecies. It should not be read as the global status of every leopard. The image is a photograph of an animal in managed care.",
      sourceName: "WWF",
      sourceTitle: "Amur leopards",
      number: "014",
      image: "assets/animals/amur-leopard.jpg",
      alt: "Original realistic illustration of an Amur leopard in a snowy mountain forest",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "65% 50%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "red-panda",
      name: "Red panda",
      scientific: "Ailurus fulgens",
      status: "endangered",
      conservation: "Endangered",
      place: "Eastern Himalayas",
      range: "Temperate mountain forests of the Himalayas and nearby regions",
      date: "Still with us",
      dateDetail: "Endangered; forest loss and trapping threaten its future",
      summary:
        "A russet flash among the branches. A forest home worth keeping.",
      paragraphs: [
        "Red pandas are skilled tree dwellers with thick reddish fur and long tails used for balance. Their mountain forest habitat provides nesting trees and bamboo.",
        "Forest clearance removes food and shelter. They can also be caught in traps intended for other animals, making habitat protection and community conservation especially important.",
      ],
      evidence:
        "WWF lists Ailurus fulgens as Endangered. Taxonomic interpretations and regional assessments can differ; this archive follows the named source rather than treating its label as live monitoring.",
      sourceName: "WWF",
      sourceTitle: "Red pandas",
      number: "015",
      image: "assets/animals/red-panda.jpg",
      alt: "Original realistic illustration of a red panda on a mossy branch in a mountain forest",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "45% 50%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "mountain-gorilla",
      name: "Mountain gorilla",
      scientific: "Gorilla beringei beringei",
      status: "endangered",
      conservation: "Endangered",
      place: "Central & East Africa",
      range: "Virunga Mountains and Bwindi Impenetrable National Park",
      date: "Still with us",
      dateDetail: "Endangered; recovery depends on continuing conservation",
      summary: "A recovery story. A reminder that protection must continue.",
      paragraphs: [
        "Mountain gorillas are an eastern gorilla subspecies living in forested mountain landscapes. Their thick fur helps them cope with cold conditions.",
        "Decades of coordinated conservation have helped their population recover. Habitat pressure, disease, hunting, and regional conflict still make continued protection essential.",
      ],
      evidence:
        "Mountain gorillas are listed as Endangered, rather than Critically Endangered, in the cited source. Their improved status does not mean their survival is secure without conservation.",
      sourceName: "WWF",
      sourceTitle: "Mountain gorillas",
      number: "016",
      image: "assets/animals/mountain-gorilla.jpg",
      alt: "Original realistic illustration of a mountain gorilla in misty mountain rainforest",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "50% 42%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "bornean-orangutan",
      name: "Bornean orangutan",
      scientific: "Pongo pygmaeus",
      status: "endangered",
      conservation: "Critically endangered",
      place: "Borneo",
      range: "Forests of Borneo, Indonesia and Malaysia",
      date: "Still with us",
      dateDetail:
        "Critically endangered; connected forests and protection are essential",
      summary: "A life in the canopy. An island’s forests hold its future.",
      paragraphs: [
        "Bornean orangutans spend much of their lives in trees. Large stretches of forest provide food and opportunities to find mates.",
        "Deforestation and hunting are major threats. Protecting connected forest landscapes helps preserve the space these great apes need.",
      ],
      evidence:
        "Bornean, Sumatran, and Tapanuli orangutans are distinct species. WWF reports all three as Critically Endangered; this story focuses on Pongo pygmaeus in Borneo.",
      sourceName: "WWF UK",
      sourceTitle: "Top 10 facts about orangutans",
      number: "017",
      image: "assets/animals/bornean-orangutan.jpg",
      alt: "Original realistic illustration of a Bornean orangutan in rainforest canopy",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "50% 38%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "hawksbill",
      name: "Hawksbill turtle",
      scientific: "Eretmochelys imbricata",
      status: "endangered",
      conservation: "Critically endangered",
      place: "Tropical oceans",
      range: "Tropical seas, especially coral reef habitats",
      date: "Still with us",
      dateDetail:
        "Critically endangered; trade and accidental fishing capture remain threats",
      summary: "A reef traveller. A living link in the ocean’s intricate web.",
      paragraphs: [
        "Hawksbill turtles use their narrow beaks to reach sponges in reef crevices. Their feeding helps maintain the balance of coral reef communities.",
        "Demand for tortoiseshell and accidental capture in fishing gear threaten them. Protecting marine habitats and reducing these pressures helps their story continue.",
      ],
      evidence:
        "WWF lists the species as Critically Endangered. Risk and recovery vary between nesting populations; the global label is not a count of turtles at any one reef.",
      sourceName: "WWF",
      sourceTitle: "Hawksbill turtles",
      number: "018",
      image: "assets/animals/hawksbill.jpg",
      alt: "Original realistic illustration of a hawksbill turtle above coral reef",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "72% 70%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "blue-whale",
      name: "Blue whale",
      scientific: "Balaenoptera musculus",
      status: "endangered",
      conservation: "Endangered",
      place: "World’s oceans",
      range: "Ocean habitats across the globe",
      date: "Still with us",
      dateDetail:
        "Endangered; ship strikes and fishing-gear entanglement remain threats",
      summary: "The largest living animal. A vast ocean is not a safe ocean.",
      paragraphs: [
        "Blue whales are the largest animals on the planet. They feed on tiny krill, linking their lives to the ocean’s changing food systems.",
        "Past commercial whaling heavily depleted their populations. Today, collisions with ships, entanglement in fishing gear, and environmental change continue to threaten them.",
      ],
      evidence:
        "The global species is listed as Endangered by WWF. Different populations face different conditions, and population estimates are not presented here as a live count.",
      sourceName: "WWF",
      sourceTitle: "Blue whales",
      number: "019",
      image: "assets/animals/blue-whale.jpg",
      alt: "Original realistic illustration of a blue whale surfacing in open ocean",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "50% 50%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
    {
      id: "vaquita",
      name: "Vaquita",
      scientific: "Phocoena sinus",
      status: "endangered",
      conservation: "Critically endangered",
      place: "Gulf of California",
      range: "Northern Gulf of California, Mexico",
      date: "Still with us",
      dateDetail:
        "Critically endangered; eliminating gillnet bycatch is urgent",
      summary: "A small porpoise. A tiny range. An urgent chance to act.",
      paragraphs: [
        "The vaquita is a small porpoise found only in the northern Gulf of California. Its entire wild range lies within this one part of Mexico.",
        "Gillnets set for other marine animals can trap and drown vaquitas. Removing that threat throughout their habitat is central to their survival.",
      ],
      evidence:
        "WWF lists the vaquita as Critically Endangered. Counts are difficult and change between surveys, so this story avoids presenting a precise number as current.",
      sourceName: "WWF",
      sourceTitle: "Vaquita",
      number: "020",
      image: "assets/animals/vaquita.jpg",
      alt: "Original realistic illustration of a vaquita swimming underwater near the surface",
      imageKind: "Original wildlife illustration",
      imageWidth: 1448,
      imageHeight: 1086,
      imagePosition: "50% 65%",
      imageFit: "cover",
      imageBackground: "#f1eee5",
    },
  ],
  causes: {
    habitat: {
      number: "01",
      image: "habitat.png",
      title: "A home becomes a fragment.",
      description:
        "Changes to land and sea use can remove or divide habitats, leaving wildlife with less space, food, and shelter.",
      action: "A useful response: protect and reconnect habitats.",
    },
    exploitation: {
      number: "02",
      image: "hunt.png",
      title: "Taken faster than nature recovers.",
      description:
        "Unsustainable hunting, fishing, and harvesting can reduce populations faster than they can replenish themselves.",
      action:
        "A useful response: reduce illegal and unsustainable exploitation.",
    },
    climate: {
      number: "03",
      image: "climate.png",
      title: "A changing world, a shifting home.",
      description:
        "Changing temperatures and rainfall reshape ecosystems. These pressures can compound habitat loss and other threats.",
      action:
        "A useful response: address emissions and protect resilient habitats.",
    },
    pollution: {
      number: "04",
      image: "pollution.png",
      title: "The damage travels.",
      description:
        "Pollution can degrade the water, air, and land that species depend on, adding pressure to already stressed ecosystems.",
      action: "A useful response: prevent pollution at its source.",
    },
    invasive: {
      number: "05",
      image: "human_impact_wide.png",
      title: "An arrival changes everything.",
      description:
        "Introduced species can become invasive, disrupting native ecosystems through predation, competition, or disease.",
      action:
        "A useful response: prevent introductions and manage invasive species.",
    },
  },
  questions: [
    {
      question: "Which island was home to the dodo?",
      options: ["Madagascar", "Mauritius", "Australia"],
      correct: 1,
      explanation: "The dodo lived on Mauritius in the Indian Ocean.",
      species: "dodo",
    },
    {
      question: "Smilodon is best described as…",
      options: [
        "An extinct tiger subspecies",
        "A modern leopard",
        "A prehistoric saber-toothed cat",
      ],
      correct: 2,
      explanation:
        "Smilodon belonged to a saber-toothed lineage distinct from modern tigers.",
      species: "smilodon",
    },
    {
      question: "An endangered species is…",
      options: [
        "Still living, but at high risk of extinction",
        "Already extinct",
        "Found only in museums",
      ],
      correct: 0,
      explanation:
        "Endangered species still exist. Their future depends on addressing the threats they face.",
      species: "tiger",
    },
  ],
};
